# Disciplina: Ciência de Dados (DCA-0131)
Prof. Luiz Affonso Guedes

### Departamento de Engenharia de Computação e Automação - DCA

UFRN - 2025

*OBS: Favor fazer cópia do notebook antes de alterá-lo.

## Aula 6 - Pacote Pandas - Parte III
- Conceitos de tratamento avançado de dados: join, merge, groupby, concatenação.

- Exemplo de aplicação.

## Funcionalidades Avançadas para Tratamento de Dataframes
Apresentar as funcionalidades de manipulação de tabelas do tipo GroupBy, Merge, Join e Concatenação.

### GroupBy: Split, Apply, Combine

As agregações simples em muitos casos podem ser suficientes, mas muitas vezes é preciso agregar diversas tabelas condicionalmente em algum rótulo ou índice: isso é implementado na chamada operação groupby. O nome "groupBy" vem de um comando na linguagem do banco de dados SQL, que representa a seguinte sequência de operações: dividir, aplicar, combinar.

Passos: split, apply, combine.
- O passo 'split' envolve dividir e agrupar um DataFrame dependendo do valor da chave especificada.
- O passo 'apply' envolve a computação de alguma função, geralmente um agregado, transformação ou filtragem, dentro dos grupos individuais.
- O passo 'combine' combina os resultados dessas operações em array de saída.

In [2]:
# Exemplo: Importanto Pandas

from pandas import Series, DataFrame
import pandas as pd

In [3]:
# Exemplo de uso de GroupBy
# Definição de um DataFrame Pandas

df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [4]:
# Dividindo em grupos em função da coluna-chave 'key'
df.groupby('key')

Observe que o retorno é um objeto do tipo groupyby.

In [5]:
# Aplicando uma operação sobre o dado já agrupado (apply)
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [6]:
# Aplicando uma operação sobre o dado já agrupado (apply)
df.groupby('key').max()

     data
key
A       3
B       4
C       5

### Abordagem: Agregar, Filtrar, Transformar, Aplicar.
Exemplo de uso dessa abordagem com o dataframe planets, proveniente do pacote Seaborn.

In [7]:
# Arquivo sobre planetas do pacote Seaborn

import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [8]:
# Exemplo com a base de dados 'planets'
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [9]:
# Divide em grupos pela coluna-chave 'method'
planets.groupby('method').head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300000,7.10,77.40,2006
1,Radial Velocity,1,874.774000,2.21,56.95,2008
2,Radial Velocity,1,763.000000,2.60,19.84,2011
3,Radial Velocity,1,326.030000,19.40,110.62,2007
4,Radial Velocity,1,516.220000,10.50,119.47,2009
29,Imaging,1,NaN,NaN,45.52,2005
30,Imaging,1,NaN,NaN,165.00,2007
31,Imaging,1,NaN,NaN,140.00,2004
32,Eclipse Timing Variations,1,10220.000000,6.05,NaN,2009
33,Imaging,1,NaN,NaN,NaN,2008
34,Imaging,1,NaN,NaN,145.00,2013
37,Eclipse Timing Variations,2,5767.000000,NaN,130.72,2008
38,Eclipse Timing Variations,2,3321.000000,NaN,130.72,2008
39,Eclipse Timing Variations,2,5573.550000,NaN,500.00,2010
40,Eclipse Timing Variations,2,2883.500000,NaN,500.00,2010
91,Transit,1,1.508956,NaN,NaN,2008
92,Transit,1,1.742994,NaN,200.00,2008
93,Transit,1,4.256800,NaN,680.00,2008
94,Transit,1,9.202050,NaN,NaN,2008
95,Transit,1,4.037896,NaN,NaN,2009
113,Astrometry,1,246.360000,NaN,20.77,2013
537,Astrometry,1,1016.000000,NaN,14.98,2010
680,Transit Timing Variations,2,160.000000,NaN,2119.00,2011
736,Transit Timing Variations,2,57.011000,NaN,855.00,2012
749,Transit Timing Variations,3,NaN,NaN,NaN,2014
787,Orbital Brightness Modulation,2,0.240104,NaN,1180.00,2011
788,Orbital Brightness Modulation,2,0.342887,NaN,1180.00,2011
792,Orbital Brightness Modulation,1,1.544929,NaN,NaN,2013
813,Transit Timing Variations,2,22.339500,NaN,339.00,2013
902,Microlensing,1,NaN,NaN,NaN,2008
903,Microlensing,1,NaN,NaN,NaN,2008
904,Microlensing,1,NaN,NaN,NaN,2009
905,Microlensing,1,NaN,NaN,3600.00,2013
906,Microlensing,1,2780.000000,NaN,NaN,2011
941,Pulsar Timing,3,25.262000,NaN,NaN,1992
942,Pulsar Timing,3,66.541900,NaN,NaN,1992
943,Pulsar Timing,3,98.211400,NaN,NaN,1994
944,Pulsar Timing,1,36525.000000,NaN,NaN,2003
945,Pulsar Timing,1,0.090706,NaN,1200.00,2011
958,Pulsation Timing Variations,1,1170.000000,NaN,NaN,2007

In [10]:
# Divide em grupos pela coluna-chave 'method' e filtrar
planets.groupby('method')['orbital_period']

In [11]:
# Divide em grupos pela coluna-chave 'method', filtrar e aplicar
print("Fornece a mediana dos perídos orbitais obtidos pelos diversos existentes no dataframe\n")
planets.groupby('method')['orbital_period'].median()

Fornece a mediana dos perídos orbitais obtidos pelos diversos existentes no dataframe

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [12]:
# Divide em grupos pela coluna-chave 'method', filtrar e aplicar
planets.groupby('method')['year'].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,2011.500000,2.121320,2010.0,2010.75,2011.5,2012.25,2013.0
Eclipse Timing Variations,9.0,2010.000000,1.414214,2008.0,2009.00,2010.0,2011.00,2012.0
Imaging,38.0,2009.131579,2.781901,2004.0,2008.00,2009.0,2011.00,2013.0
Microlensing,23.0,2009.782609,2.859697,2004.0,2008.00,2010.0,2012.00,2013.0
Orbital Brightness Modulation,3.0,2011.666667,1.154701,2011.0,2011.00,2011.0,2012.00,2013.0
Pulsar Timing,5.0,1998.400000,8.384510,1992.0,1992.00,1994.0,2003.00,2011.0
Pulsation Timing Variations,1.0,2007.000000,NaN,2007.0,2007.00,2007.0,2007.00,2007.0
Radial Velocity,553.0,2007.518987,4.249052,1989.0,2005.00,2009.0,2011.00,2014.0
Transit,397.0,2011.236776,2.077867,2002.0,2010.00,2012.0,2013.00,2014.0
Transit Timing Variations,4.0,2012.500000,1.290994,2011.0,2011.75,2012.5,2013.25,2014.0

In [13]:
# Divide em grupos pela coluna-chave 'method', filtrar e aplicar
planets.groupby('method')['year'].describe().unstack()

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

### Combinando Datasets: Merge and Join
Alguns dos mais interessantes estudos de dados provêm da combinação de diferentes fontes de dados. Essas operações podem envolver qualquer coisa, desde concatenação muito direta
de dois conjuntos de dados diferentes para junções e fusões de estilo de banco de dados mais complicadas, que lidam com sobreposições entre os conjuntos de dados.

Pandas possui funções e métodos
que tornam esse tipo de manipulação de dados rápida e prática: funções de concatenação, merge e join.

In [14]:
import pandas as pd
import numpy as np

In [15]:
# Definição de uma função para criação de DataFrames
def make_df(cols, ind):
   data = {c: [str(c) + str(i) for i in ind]
       for c in cols}
   return pd.DataFrame(data, ind)

In [16]:
# Exemplo de DataFrame
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

### Funcionalidade de Concatenação

In [17]:
print("Exemplo de concatenação com NumPy")
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

Exemplo de concatenação com NumPy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
print("Exemplo de concatenação com NumPy, especificando o eixo")
x = [[1, 2],
[3, 4]]
# np.concatenate([x, x], axis=1) # Horizontal
np.concatenate([x, x], axis=0) # Vertical

Exemplo de concatenação com NumPy, especificando o eixo

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### Observação:
Pandas tem uma função pd.concat(), a qual tem sintaxe similar à np.concatenate, mas contém váriais opções de parâmetros.

Assinatura da função em Pandas v0.18

```python
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
keys=None, levels=None, names=None, verify_integrity=False,
copy=True)
```

In [19]:
print("Exemplo de uso da função de concatenação de tipo Serie em Pandas")
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

Exemplo de uso da função de concatenação de tipo Serie em Pandas

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [20]:
print("Exemplo de uso da função de concatenação de tipo DataFrames em Pandas")
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1)
print()
print(df2)
print()
print(pd.concat([df1, df2]))

Exemplo de uso da função de concatenação de tipo DataFrames em Pandas
    A   B
1  A1  B1
2  A2  B2

    A   B
3  A3  B3
4  A4  B4

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

### Observação:
Por default, a concatenação é realizada por linha no DataFrame (axis=0).

Como no  np.concatenate(), pd.concat() permite especificar o eixo ao qual será realizada a concatenação.

In [21]:
print("Exemplo de uso da função de concatenação de tipo DataFrames em Pandas")

print(" - com seleção do eixo 1")

df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3)
print()
print(df4)
print()
print("Concatenação pelo eixo 1")
print(pd.concat([df3, df4], axis=1))

Exemplo de uso da função de concatenação de tipo DataFrames em Pandas
 - com seleção do eixo 1
    A   B
0  A0  B0
1  A1  B1

    C   D
0  C0  D0
1  C1  D1

Concatenação pelo eixo 1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

### Observação:
Uma diferença importante entre np.concatenate() e pd.concat() é que em Pandas a concatenação preserva os índices, mesmo que o resultado tenha índices duplicados.

In [22]:
print("Exemplo de concatenação")
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index # índices duplicados
print("\nValor de X")
print(x)
print("\nValor de Y")
print(y)
print("\nConcatenação de X e Y")
print(pd.concat([x, y]))

Exemplo de concatenação

Valor de X
    A   B
0  A0  B0
1  A1  B1

Valor de Y
    A   B
0  A2  B2
1  A3  B3

Concatenação de X e Y
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [23]:
print("\nConcatenação de X e Y, ignorando o índice")
print(pd.concat([x, y], ignore_index=True))

Concatenação de X e Y, ignorando o índice
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

### Observação:
Chaves MultiIndex - Outra alternativa é o uso da opção 'keys' para especificar um label para a fonte de dados.

In [24]:
print("Concatenação com especificação de labels multiIndex")
print(pd.concat([x, y], keys=['x', 'y']))

Concatenação com especificação de labels multiIndex
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

### Funcionalidade Concatenação com Join
Nos exemplos anteriores concatenamos DataFrames que compartilham os mesmos nomes de colunas. Na prática, porém, dados vêm de diferentes fontes e podem ter diferentes conjuntos de nomes de colunas. O método pd.concat() oferece várias opções para tratar esses casos.

In [25]:
print("DataFrames com nomes de colunas diferentes")
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print("\nDataFrame dfe5")
print(df5)
print("\nDataFrame dfe6")
print(df6)
print("\nDataFrame concatenado de dfe5 e df6")
print(pd.concat([df5, df6]))

DataFrames com nomes de colunas diferentes

DataFrame dfe5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

DataFrame dfe6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

DataFrame concatenado de dfe5 e df6
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

### Observação:
Por default, atribui-se NaN para as entradas para as quais dados não são disponíveis. Para mudar isto, nós podemos especificar uma das várias opções para o parâmetros 'join' e 'join_axes' na função de concatenação.

Por default, o 'join' é a união das coluna (join='outer'), mas nós podemos mudar isto para uma interseção de colunas usando join='inner'.

In [26]:
print("\nDataFrame concatenado de dfe5 e df6, com interseção de colunas")
print(pd.concat([df5, df6], join='inner'))

DataFrame concatenado de dfe5 e df6, com interseção de colunas
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [27]:
print("Podemos concatenar 02 dataFrames baseado apenas nos índices de um deles")
res = pd.concat([df5, df6], axis=1)
res = res.reindex(df5.index)
print(res)

Podemos concatenar 02 dataFrames baseado apenas nos índices de um deles
    A   B   C    B    C    D
1  A1  B1  C1  NaN  NaN  NaN
2  A2  B2  C2  NaN  NaN  NaN

## Combinando Datasets: Merge e Join

Uma característica essencial oferecida pelo Pandas é o conjunto de operações de join e merge de alto desempenho e em memória. Se você já trabalhou com bancos de dados, você deve estar familiarizado com esse tipo de interação de dados. A interface principal para isso é a função pd.merge( ), e veremos alguns exemplos de como isso pode funcionar na prática.

#### Exemplo com Álgebra Relacional

A função pd.merge() implementa um subconjunto de álgebra relaconal, que é um conjunto de regras formais para manipular dados relacionais e forma a fundamentação teórica das operações disponíveis em muitos banco de dados relacionais.

A função pd.merge() implementa três tipos de joins:
- one-to-one, joins simples com uma das colunas com os mesmos elementos.
- many-to-one, quando uma das "key columns" de um DataFrame contém entradas duplicadas.
- many-to-many, quando colunas de chaves nos dois DataFrames contêm duplicatas chaves de colunas duplicadas.

In [28]:
# Exemplo de Join one-to-one

df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
print("\nDataFrame df1")
print(df1)
print("\nDataFrame df2")
print(df2)

DataFrame df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

DataFrame df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [29]:
# Exemplo de Join one-to-one
# Agrupamento simple
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [30]:
# Many-to-one joins
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
'supervisor': ['Carly', 'Guido', 'Steve']})
print("\n dateFrame df3")
print(df3)
print("\n dateFrame df4")
print(df4)
print("\n dateFrame  df3-df4")
pd.merge(df3, df4)

 dateFrame df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

 dateFrame df4
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

 dateFrame  df3-df4

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [31]:
# Many-to-many joins
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux',
'spreadsheets', 'organization']})
print("\n DataFrame df1")
print(df1)
print("\n DataFrame df5")
print(df5)
pd.merge(df1, df5)

 DataFrame df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

 DataFrame df5
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

### Especificação do Merge usando-se Key

Por default, a função pd.merge() associa uma ou mais colunas a partir dos nomes das colunas - conceito de chave (key).

Quando não há um casamento adequado entre os nomes das colunas, é possível utilizar uma variedade de opções de parâmetros para resolver este problema.


O modo mais simples é especificar explicitamente o nome da coluna chave (key) como palavra-chave (keyword). Porém, esta opção trabalha somente se ambos os DataFrames têm o nome de coluna especificado.

In [32]:
# Exemplo de uso de keyword na função pd.merge()
print("\n DataFrame df1")
print(df1)
print("\n DataFrame df2")
print(df2)
pd.merge(df1, df2, on='employee') # Join usando o índice 'employee'

 DataFrame df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

 DataFrame df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

Palavras-chaves left_on and right_on keywords:
- quando se deseja fazer o merge de DataFrames com nomes de colunas diferente.

In [33]:
# Exemplo
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})
print(df1)
print()
print(df3)
pd.merge(df1, df3, left_on="employee", right_on="name")

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [34]:
# Eliminando a coluna redundante

pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

Palavras-chaves left_index e right_index:
-  pode-se utilizar o index como chave para fazer o merge em pd.merge().

In [35]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a)
print()
print(df2a)

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [36]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [37]:
#O método join() é equilavente ao merge(),
# mas no estilo orientado a objetos

df1a.join(df2a)

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

#### Exemplos
- O que ocorre quando um item aparece numa coluna mas não em outra?

In [38]:
# Exemplo

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])
print(df6)
print()
print(df7)
print()
pd.merge(df6, df7)

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

     name drink
0    Mary  wine
1  Joseph  beer

   name   food drink
0  Mary  bread  wine

In [39]:
# Default - interseção
pd.merge(df6, df7, how='inner')

   name   food drink
0  Mary  bread  wine

In [40]:
# Uso da união

pd.merge(df6, df7, how='outer')

     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [41]:
# Associação pela coluna da esquerda
pd.merge(df6, df7, how='left')

    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [42]:
# Associação pela coluna da direita
pd.merge(df6, df7, how='right')

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [43]:
# Exemplo de uso de sufixos
# formato padrão

df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})
print(df8)
print()
print(df9)
print()
pd.merge(df8, df9, on="name")

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [44]:
# Exemplo de uso de sufixos
# Especificando os sufixos

pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

# Exercício de Aplicação: para fixação dos conteúdos apresentados

Carregue os arquivos no seguinte github: dados do EU.

https://github.com/jakevdp/data-USstates/

In [45]:
# Carregando os arquivos csv
#Código
pop = pd.read_csv('https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv')
areas = pd.read_csv('https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv')
abbrevs = pd.read_csv('https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv')

In [46]:
# Verificando os conteúdos dos arquivos

print(pop.head())
print()
print(areas.head())
print()
print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

#### Passo 1. Gere um DataFrame (dfMerged), com as seguintes colunas:

**Colunas:** `state/region`, `ages`, `year`, `population`, `state`

Depois, faça as seguintes verificações

- Verificação das cinco primeiras linhas do DataFrame gerado
- Verificação se há algum dado faltando
- Verificação de quais itens de "population" estão faltando
- Verificação de quais `state/region` têm elementos na coluna `state` com data missing

In [58]:
#

### Passo 2. Gere um DataFrame (dfFinal), com as seguintes colunas:

**Colunas:** `state/region`, `ages`, `year`, `population`, `state`, `area (sq. mi)`

Depois faça as seguintes verificações
- Verificação do resultado
- Verificação se há data missing

In [57]:
#

### Passo 3. Deve haver nulos na coluna da área.
Verifique quais regiões foram ignoradas.

In [59]:
#

### Passo 4. Há campos na coluna de área no DataFrame com data missing.
Para resolver esse tipo de problema, podemos inserir o valor apropriado (usando a soma de todas as áreas de estado, por exemplo), mas neste caso, simplesmente elimite os campos com valores nulos.

In [ ]:
#

### Passo 5. Obtenha um DataFrame (data2010) da população dos EU em 2010 (apenas o total por estados).
- data2010(state/region, ages, year, population, state,area (sq. mi))

In [62]:
#

### Passo 6. Obtenha os 5 estados com maiores densidades populacionais em 2010 (em order decrescente)

In [52]:
# Código

### Passo 7. Obtenha os 5 estados com menores densidades populacionais em 2010 (em order decrescente)

In [53]:
# Código

### Passo 8. Obtenha os 05 estados com maiores proporções de jovens (under 18) em 2010 (apresente o resultado em ordem decrescente)

In [54]:
# Código

### Passo 9. Obtenha a média das populações (total e under18) por estado.
- Sugestão: Utilizar groupBy.

In [55]:
# Código

### Passo 10. Trace um gráfico em relação ao ano (year) do crescimento da população total e de jovens (under18) dos 05 estados mais populosos em 2010.

In [56]:
# Código